### ISSUE TITLE
Cannot build Android/NendMediationTest on Android Studio 2.1.2

### ISSUE THREAD

**Issue by justoneplanet** [fan-ADN/nendSDK-admob-mediation#1]
### メディア登録名

IO Inc.
### SDKのバージョン

```
compileSdkVersion 23
```
### クラッシュログ等

何もしてない状態だと以下のエラーがbuild時に出ます

```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

また以下を追記すると

```
        multiDexEnabled true
```

以下のエラーが出てbuildできません。

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v7/recyclerview/R$attr.class
```

**Comment by ghost** [comment]
@justoneplanet 様
ファンコミュニケーションズの逸見です。
お問い合わせいただきありがとうございました。

今回のエラーは gradleのバージョンによる問題のようでした。
修正版をアップさせていただきましたので、こちらをお試しいただければと思います。

よろしくお願いいたします。

**Comment by justoneplanet** [comment]
ご連絡ありがとうございます。

すみません。変わらずbuildできないのですがこちらの環境によるものなのでしょうか？JDKのバージョンに起因するのかと思い1.7にしてみましたが変わらず以下のようなエラーが出力されます。

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v7/recyclerview/R$attr;
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

**Comment by ghost** [comment]
@justoneplanet 様
ファンコミュニケーションズの逸見です。
ご連絡いただきありがとうございました。

昨日プッシュしました変更分はプルしていただきましたでしょうか？
build.gradleファイル
`classpath 'com.android.tools.build:gradle:2.1.2`
gradle-wrapper.propertiesファイル
`distributionUrl=https\://services.gradle.org/distributions/gradle-2.2.1-all.zip`
となっておりますでしょうか。

上記変更点をご確認いただき、Android Studioの上部メニュー**「Build > Clean Project」**を実行後、ビルドをお試しください。

よろしくお願いいたします。

**Comment by justoneplanet** [comment]
ご連絡ありがとうございます。

> 昨日プッシュしました変更分はプルしていただきましたでしょうか？

はい。変更されている事を確認しました。

> 「Build > Clean Project」を実行後、ビルドをお試しください。

はい。実行後に:app:transformClassesWithDexForDebugで以下のエラーが表示されます。

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v7/recyclerview/R$attr;
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

お忙しいところすみませんがどうぞ宜しくお願いいたします。

**Comment by ghost** [comment]
@justoneplanet 様
ファンコミュニケーションズの逸見です。
ご連絡ありがとうございます。

不要な設定ファイルが影響している可能性がありましたので、削除したプロジェクトをアップいたしました。
ローカルの履歴などの影響も考えられる為、こちらのプロジェクトを現在のフォルダとは別のフォルダにクローンしていただき、
AndroidStudioの**「Import project (Eclipse ADT,  Gradle, etc.)」**でインポートをお試しいただけますでしょうか。

度々申し訳ありません。よろしくお願いいたします。

**Comment by justoneplanet** [comment]
遅くなりましてすみません。

> AndroidStudioの「Import project (Eclipse ADT, Gradle, etc.)」でインポート

やはり以下のようなエラーがでてしまいます。

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v7/recyclerview/R$attr;
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

御社側では特に問題が起きてませんでしょうか？私の環境に依存した問題の可能性が高いという事でしょうか？

**Comment by ghost** [comment]
@justoneplanet 様
ご連絡ありがとうございます。

> 御社側では特に問題が起きてませんでしょうか？私の環境に依存した問題の可能性が高いという事でしょうか？

弊社側でも複数人の環境で試したのですが、同様のエラーは再現されませんでした。

どうしてもビルドが通らない場合は、jarファイルでの導入をお試しいただけますでしょうか。
「nendAdapter-1.2.4.jar」
「nendSDK−3.1.1.jar」
を管理画面からダウンロードしていただき、プロジェクトの **libs**フォルダに配置、
build.gradleファイルの dependencies に下記を記述していただけますでしょうか。

```
dependencies {
    compile files('libs/nendSDK-3.2.0.jar')
    compile files('libs/nendAdapter-1.2.4.jar')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.google.android.gms:play-services-ads:9.2.0'
//    compile 'net.nend.android:nend-adapter:1.2.4'
}
```

また、今回のエラーに関して調査したいのですが、差し支えなければ、エラーが起きているプロジェクトをこちらのissueに添付していただく事は可能でしょうか？
（プロジェクトフォルダをZipに圧縮していただき、テキストエリア下部の **selecting them.**から添付可能です。）

よろしくお願いいたします。

**Comment by justoneplanet** [comment]
すみません。時間があいてしまいましたが環境を作りなおしてbuildしたところ問題なくbuildできるようになりました。
